import os
import pytest
from uuid import uuid4
import httpx
import json
from unittest.mock import patch

from app.main import app
from app.core.config import settings


@pytest.mark.asyncio
async def test_reports_integration_flows():
    # Generate unique test user credentials
    email = f"tester_{uuid4().hex[:6]}@prismiq.com"
    password = "securepassword123"
    
    transport = httpx.ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        # 1. User Registration & Login
        reg_res = await client.post("/api/v1/auth/register", json={"email": email, "password": password})
        assert reg_res.status_code == 200
        
        login_res = await client.post("/api/v1/auth/login", json={"email": email, "password": password})
        assert login_res.status_code == 200
        token = login_res.json()["data"]["access_token"]
        headers = {"Authorization": f"Bearer {token}"}
        
        # 2. Upload test dataset
        csv_content = "id,name,score,age\n1,Alice,95,20\n2,Bob,88,21\n3,Charlie,92,22"
        files = {"file": ("test_report_data.csv", csv_content, "text/csv")}
        data = {
            "dataset_name": "Test Reports Dataset",
            "description": "Verification of reports generation"
        }
        upload_res = await client.post("/api/v1/datasets", data=data, files=files, headers=headers)
        assert upload_res.status_code == 200
        dataset_id = upload_res.json()["data"]["id"]
        
        # 3. Trigger Profiling, EDA, and Insights
        profile_res = await client.post(f"/api/v1/datasets/{dataset_id}/profile", headers=headers)
        assert profile_res.status_code == 200
        
        eda_res = await client.post(f"/api/v1/datasets/{dataset_id}/eda", headers=headers)
        assert eda_res.status_code == 200
        
        insights_res = await client.post(f"/api/v1/datasets/{dataset_id}/insights", headers=headers)
        assert insights_res.status_code == 200
        
        # 4. Generate JSON Report
        json_res = await client.post(
            f"/api/v1/reports/generate?dataset_id={dataset_id}&report_type=JSON",
            headers=headers
        )
        assert json_res.status_code == 200
        json_data = json_res.json()["data"]
        assert json_data["status"] == "COMPLETED"
        assert json_data["report_type"] == "JSON"
        assert json_data["checksum_algorithm"] == "SHA-256"
        assert json_data["checksum"] is not None
        assert json_data["file_size"] > 0
        assert json_data["started_at"] is not None
        assert json_data["completed_at"] is not None
        assert json_data["duration_ms"] >= 0
        assert json_data["error_message"] is None
        
        # Verify JSON file layout and metadata
        report_id = json_data["id"]
        json_filepath = os.path.join(settings.STORAGE_ROOT, "reports", "json", f"report_{report_id}.json")
        assert os.path.exists(json_filepath)
        
        with open(json_filepath, "r", encoding="utf-8") as f:
            exported_json = json.load(f)
            
        assert exported_json["metadata"]["generated_by"] == "PrismIQ"
        assert exported_json["metadata"]["report_id"] == str(report_id)
        assert exported_json["metadata"]["report_schema_version"] == "1.0"
        assert "dataset" in exported_json
        assert "quality" in exported_json
        assert "profiling" in exported_json
        assert "cleaning" in exported_json
        assert "eda" in exported_json
        assert "insights" in exported_json
        assert "dashboard" in exported_json

        # 5. Generate Excel Report
        excel_res = await client.post(
            f"/api/v1/reports/generate?dataset_id={dataset_id}&report_type=EXCEL",
            headers=headers
        )
        assert excel_res.status_code == 200
        excel_data = excel_res.json()["data"]
        assert excel_data["status"] == "COMPLETED"
        excel_filepath = os.path.join(settings.STORAGE_ROOT, "reports", "excel", f"report_{excel_data['id']}.xlsx")
        assert os.path.exists(excel_filepath)

        # 6. Generate HTML Report
        html_res = await client.post(
            f"/api/v1/reports/generate?dataset_id={dataset_id}&report_type=HTML",
            headers=headers
        )
        assert html_res.status_code == 200
        html_data = html_res.json()["data"]
        assert html_data["status"] == "COMPLETED"
        html_filepath = os.path.join(settings.STORAGE_ROOT, "reports", "html", f"report_{html_data['id']}.html")
        assert os.path.exists(html_filepath)
        
        with open(html_filepath, "r", encoding="utf-8") as f:
            html_content = f.read()
        assert "Report Generated By PrismIQ" in html_content
        assert str(html_data["id"]) in html_content

        # 7. Generate PDF Report
        pdf_res = await client.post(
            f"/api/v1/reports/generate?dataset_id={dataset_id}&report_type=PDF",
            headers=headers
        )
        assert pdf_res.status_code == 200
        pdf_data = pdf_res.json()["data"]
        assert pdf_data["status"] == "COMPLETED"
        pdf_filepath = os.path.join(settings.STORAGE_ROOT, "reports", "pdf", f"report_{pdf_res.json()['data']['id']}.pdf")
        assert os.path.exists(pdf_filepath)

        # 8. List Reports & Pagination
        list_res = await client.get("/api/v1/reports?page=1&limit=5", headers=headers)
        assert list_res.status_code == 200
        assert len(list_res.json()["data"]) >= 4

        list_filtered = await client.get(f"/api/v1/reports?format=JSON&dataset_id={dataset_id}", headers=headers)
        assert list_filtered.status_code == 200
        assert len(list_filtered.json()["data"]) == 1

        # 9. Download Report
        dl_res = await client.get(f"/api/v1/reports/{report_id}/download", headers=headers)
        assert dl_res.status_code == 200
        assert dl_res.headers.get("content-type") == "application/octet-stream"

        # 10. Delete Report
        del_res = await client.delete(f"/api/v1/reports/{report_id}", headers=headers)
        assert del_res.status_code == 200
        assert not os.path.exists(json_filepath)

        # Clean up files
        for filepath in [excel_filepath, html_filepath, pdf_filepath]:
            if os.path.exists(filepath):
                os.remove(filepath)

        # 11. Invalid Dataset ID
        bad_id = uuid4()
        res_bad_id = await client.post(f"/api/v1/reports/generate?dataset_id={bad_id}&report_type=JSON", headers=headers)
        assert res_bad_id.status_code == 404
        
        # 12. Unsupported Export Format
        res_bad_fmt = await client.post(f"/api/v1/reports/generate?dataset_id={dataset_id}&report_type=PNG", headers=headers)
        assert res_bad_fmt.status_code == 400

        # 13. Verification of status transition to FAILED and partial file removal
        with patch("app.services.reports.ReportsService._generate_json", side_effect=Exception("Mocked writing failure")):
            res_fail = await client.post(
                f"/api/v1/reports/generate?dataset_id={dataset_id}&report_type=JSON",
                headers=headers
            )
            # Generation failure returns 400
            assert res_fail.status_code == 400
            assert "Failed to generate report" in res_fail.json()["message"]

            # Query list of reports to inspect the failed database record
            list_res = await client.get(f"/api/v1/reports?dataset_id={dataset_id}", headers=headers)
            assert list_res.status_code == 200
            # Filter specifically for the failed JSON report
            reports = [r for r in list_res.json()["data"] if r["status"] == "FAILED"]
            assert len(reports) == 1
            report_rec = reports[0]
            assert report_rec["status"] == "FAILED"
            assert "Mocked writing failure" in report_rec["error_message"]
            assert report_rec["duration_ms"] >= 0
            
            # Verify file does not exist on storage
            report_filepath = os.path.join(settings.STORAGE_ROOT, "reports", "json", f"report_{report_rec['id']}.json")
            assert not os.path.exists(report_filepath)

        # 14. Verify dataset comparison endpoint
        compare_res = await client.get(
            f"/api/v1/datasets/{dataset_id}/compare?v1=1&v2=1",
            headers=headers
        )
        assert compare_res.status_code == 200
        compare_data = compare_res.json()["data"]
        assert "version_difference" in compare_data
        assert "profiling_difference" in compare_data
        assert "insights_difference" in compare_data
        assert compare_data["version_difference"]["changed_rows"] == 0
        assert compare_data["version_difference"]["added_rows"] == 0
        assert compare_data["version_difference"]["removed_rows"] == 0

