"""create_data_profiles_table

Revision ID: 21eb3583bb6d
Revises: 8f2e1a62da0c
Create Date: 2026-07-15 15:55:46.230687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21eb3583bb6d'
down_revision: Union[str, None] = '8f2e1a62da0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_profiles',
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('missing_values', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('memory_usage_bytes', sa.Integer(), nullable=False),
    sa.Column('column_summary', sa.JSON(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_profiles')
    # ### end Alembic commands ###
